import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F8F7F4",
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingTop: 60,
    paddingBottom: 20,
    backgroundColor: "#FFFFFF",
  },
  greeting: {
    fontSize: 14,
    color: "#736F6C",
  },
  title: {
    fontSize: 28,
    fontWeight: "bold",
    color: "#1C1B1F",
  },
  settingsButton: {
    padding: 8,
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    padding: 16,
    paddingBottom: 32,
  },
  analyzeCta: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "#1976D2",
    borderRadius: 12,
    padding: 20,
    marginBottom: 24,
    elevation: 4,
    shadowColor: "#1976D2",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
  },
  analyzeCtaContent: {
    flexDirection: "row",
    alignItems: "center",
    gap: 16,
  },
  analyzeCtaText: {
    gap: 2,
  },
  analyzeCtaTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#FFFFFF",
  },
  analyzeCtaSubtitle: {
    fontSize: 13,
    color: "rgba(255,255,255,0.8)",
  },
  section: {
    marginBottom: 24,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: "#1C1B1F",
    marginBottom: 12,
  },
  latestCard: {
    backgroundColor: "#FEFEFE",
    borderRadius: 12,
    padding: 16,
    elevation: 2,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.12,
    shadowRadius: 6,
  },
  latestHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 8,
  },
  latestDate: {
    fontSize: 13,
    color: "#736F6C",
  },
  complianceBadge: {
    backgroundColor: "#E8F5E9",
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 8,
  },
  complianceText: {
    fontSize: 12,
    fontWeight: "600",
    color: "#4CAF50",
  },
  latestTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: "#1C1B1F",
    marginBottom: 4,
  },
  latestStats: {
    fontSize: 14,
    color: "#49454F",
    marginBottom: 12,
  },
  gradesRow: {
    flexDirection: "row",
    justifyContent: "space-around",
    paddingVertical: 12,
    borderTopWidth: 1,
    borderTopColor: "#EDECE9",
    borderBottomWidth: 1,
    borderBottomColor: "#EDECE9",
    marginBottom: 12,
  },
  gradeItem: {
    alignItems: "center",
    gap: 4,
  },
  gradeLabel: {
    fontSize: 11,
    color: "#9A9693",
    fontWeight: "500",
  },
  gradeBadge: {
    width: 28,
    height: 28,
    borderRadius: 14,
    justifyContent: "center",
    alignItems: "center",
  },
  gradeText: {
    fontSize: 14,
    fontWeight: "bold",
    color: "#FFFFFF",
  },
  viewDetailsRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: 4,
  },
  viewDetailsText: {
    fontSize: 14,
    color: "#1976D2",
    fontWeight: "500",
  },
  emptyCard: {
    backgroundColor: "#FEFEFE",
    borderRadius: 12,
    padding: 32,
    alignItems: "center",
    elevation: 2,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.12,
    shadowRadius: 6,
  },
  emptyText: {
    fontSize: 16,
    fontWeight: "600",
    color: "#49454F",
  },
  emptyHint: {
    fontSize: 14,
    color: "#9A9693",
    marginTop: 4,
  },
  quickActionsRow: {
    flexDirection: "row",
    gap: 12,
  },
  quickAction: {
    flex: 1,
    backgroundColor: "#FEFEFE",
    borderRadius: 12,
    padding: 16,
    alignItems: "center",
    elevation: 2,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.12,
    shadowRadius: 3,
  },
  quickActionLabel: {
    fontSize: 11,
    color: "#49454F",
    fontWeight: "500",
    marginTop: 4,
  },
  toolsRow: {
    flexDirection: "row",
    gap: 12,
  },
  toolCard: {
    flex: 1,
    backgroundColor: "#FEFEFE",
    borderRadius: 12,
    padding: 20,
    alignItems: "center",
    elevation: 2,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.12,
    shadowRadius: 6,
  },
  toolTitle: {
    fontSize: 16,
    fontWeight: "600",
    color: "#1C1B1F",
    marginTop: 8,
    marginBottom: 2,
  },
  toolSubtitle: {
    fontSize: 12,
    color: "#736F6C",
  },
  onboardingCta: {
    alignItems: "center",
    backgroundColor: "#1976D2",
    borderRadius: 16,
    padding: 32,
    marginBottom: 24,
    elevation: 4,
    shadowColor: "#1976D2",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    gap: 16,
  },
  onboardingCtaTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: "#FFFFFF",
    textAlign: "center",
    lineHeight: 26,
  },
  onboardingCtaButton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FEFEFE",
    borderRadius: 24,
    paddingHorizontal: 24,
    paddingVertical: 12,
    gap: 4,
    marginTop: 4,
  },
  onboardingCtaButtonLabel: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#1976D2",
  },
  valuePropCard: {
    backgroundColor: "#FEFEFE",
    borderRadius: 12,
    padding: 20,
    marginBottom: 24,
    elevation: 2,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.12,
    shadowRadius: 6,
  },
  valuePropText: {
    fontSize: 14,
    color: "#49454F",
    lineHeight: 22,
    textAlign: "center",
  },
});
