import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F8F7F4",
  },
  content: {
    padding: 16,
    paddingBottom: 32,
  },
  summaryRow: {
    flexDirection: "row",
    justifyContent: "space-around",
    backgroundColor: "#FEFEFE",
    borderRadius: 12,
    padding: 20,
    marginBottom: 16,
    elevation: 2,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.12,
    shadowRadius: 6,
  },
  summaryStat: {
    alignItems: "center",
  },
  summaryValue: {
    fontSize: 32,
    fontWeight: "800",
    color: "#1976D2",
    letterSpacing: -0.5,
  },
  summaryLabel: {
    fontSize: 13,
    color: "#49454F",
    marginTop: 4,
    textTransform: "uppercase" as const,
    letterSpacing: 0.5,
    fontWeight: "500",
  },
  glanceCard: {
    backgroundColor: "#E3F2FD",
    borderRadius: 12,
    padding: 16,
    marginBottom: 24,
    flexDirection: "row" as const,
    alignItems: "center" as const,
    borderLeftWidth: 3,
    borderLeftColor: "#90CAF9",
  },
  glanceTextContainer: {
    flex: 1,
  },
  glanceText: {
    fontSize: 15,
    fontWeight: "500",
    color: "#1565C0",
    lineHeight: 22,
  },
  glanceCTA: {
    fontSize: 13,
    fontWeight: "600",
    color: "#1976D2",
    marginTop: 6,
  },
  glanceChevron: {
    marginLeft: 8,
    fontSize: 20,
    color: "#1976D2",
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: "600",
    color: "#1C1B1F",
    marginBottom: 12,
  },
  metricsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginBottom: 24,
  },
  hrZonesContainer: {
    marginBottom: 24,
  },
  metricCard: {
    width: "47%",
    backgroundColor: "#FEFEFE",
    borderRadius: 10,
    padding: 12,
    elevation: 1,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 3,
  },
  metricCardExpanded: {
    width: "100%",
    elevation: 4,
    shadowOpacity: 0.125,
  },
  metricHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  metricLabel: {
    fontSize: 12,
    color: "#49454F",
    marginBottom: 8,
  },
  expandIndicator: {
    fontSize: 18,
    color: "#49454F",
    fontWeight: "500",
  },
  metricRow: {
    flexDirection: "row",
    alignItems: "baseline",
    gap: 4,
  },
  metricValue: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#1C1B1F",
  },
  metricUnit: {
    fontSize: 14,
    color: "#49454F",
  },
  gradeBadge: {
    marginLeft: "auto",
    width: 28,
    height: 28,
    borderRadius: 14,
    justifyContent: "center",
    alignItems: "center",
  },
  gradeText: {
    fontSize: 14,
    fontWeight: "bold",
    color: "#FFFFFF",
  },
  expandedContent: {
    marginTop: 16,
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: "#DBD9D6",
  },
  thresholdsContainer: {
    marginBottom: 12,
  },
  expandedLabel: {
    fontSize: 11,
    fontWeight: "600",
    color: "#49454F",
    textTransform: "uppercase",
    letterSpacing: 0.5,
    marginBottom: 8,
  },
  thresholdsList: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  thresholdItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingVertical: 4,
    paddingHorizontal: 8,
    borderRadius: 6,
    backgroundColor: "#F3F2EF",
  },
  thresholdItemActive: {
    backgroundColor: "#E3F2FD",
  },
  thresholdBadge: {
    width: 20,
    height: 20,
    borderRadius: 10,
    justifyContent: "center",
    alignItems: "center",
  },
  thresholdBadgeText: {
    fontSize: 11,
    fontWeight: "bold",
    color: "#FFFFFF",
  },
  thresholdValue: {
    fontSize: 12,
    color: "#49454F",
  },
  thresholdValueActive: {
    fontWeight: "600",
    color: "#1565C0",
  },
  whyContainer: {
    marginBottom: 12,
  },
  whyText: {
    fontSize: 13,
    color: "#1C1B1F",
    lineHeight: 18,
  },
  coachingContainer: {
    backgroundColor: "#FFF8E1",
    borderRadius: 8,
    padding: 12,
    borderLeftWidth: 3,
    borderLeftColor: "#FFB300",
  },
  coachingLabel: {
    fontSize: 11,
    fontWeight: "600",
    color: "#FF8F00",
    textTransform: "uppercase",
    letterSpacing: 0.5,
    marginBottom: 4,
  },
  coachingText: {
    fontSize: 13,
    color: "#5D4037",
    lineHeight: 18,
  },
  complianceError: {
    backgroundColor: "#FFF3E0",
    borderRadius: 12,
    padding: 16,
    marginTop: 16,
    borderLeftWidth: 4,
    borderLeftColor: "#FF9800",
  },
  complianceErrorTitle: {
    fontSize: 14,
    fontWeight: "600",
    color: "#E65100",
    marginBottom: 4,
  },
  complianceErrorText: {
    fontSize: 13,
    color: "#BF360C",
  },
});
